SET search_path TO public;

BEGIN;

INSERT INTO users (firebase_uid, email, display_name, photo_url, email_verified, role, created_at) VALUES 
('uid_admin', 'admin@doculens.pe', 'Admin', NULL, TRUE, 'ADMIN', NOW()),
('uid_usuario1', 'usuario1@doculens.pe', 'Usuario 1', NULL, TRUE, 'USER', NOW()),
('uid_usuario2', 'usuario2@doculens.pe', 'Usuario 2', NULL, TRUE, 'USER', NOW()),
('uid_usuario3', 'usuario3@doculens.pe', 'Usuario 3', NULL, TRUE, 'USER', NOW()),
('uid_usuario4', 'usuario4@doculens.pe', 'Usuario 4', NULL, TRUE, 'USER', NOW()),
('uid_usuario5', 'usuario5@doculens.pe', 'Usuario 5', NULL, TRUE, 'USER', NOW()),
('uid_usuario6', 'usuario6@doculens.pe', 'Usuario 6', NULL, TRUE, 'ADMIN', NOW()),
('uid_usuario7', 'usuario7@doculens.pe', 'Usuario 7', NULL, TRUE, 'USER', NOW()),
('uid_usuario8', 'usuario8@doculens.pe', 'Usuario 8', NULL, TRUE, 'USER', NOW()),
('uid_usuario9', 'usuario9@doculens.pe', 'Usuario 9', NULL, TRUE, 'USER', NOW()),
('uid_usuario10', 'usuario10@doculens.pe', 'Usuario 10', NULL, TRUE, 'USER', NOW()),
('uid_usuario11', 'usuario11@doculens.pe', 'Usuario 11', NULL, TRUE, 'USER', NOW()),
('uid_usuario12', 'usuario12@doculens.pe', 'Usuario 12', NULL, TRUE, 'USER', NOW()),
('uid_usuario13', 'usuario13@doculens.pe', 'Usuario 13', NULL, TRUE, 'USER', NOW()),
('uid_usuario14', 'usuario14@doculens.pe', 'Usuario 14', NULL, TRUE, 'USER', NOW());

INSERT INTO folders (user_id, name, parent_id, created_at) VALUES 
(1, 'Documentos', NULL, NOW()),
(1, 'Facturas', 1, NOW()),
(1, '2024', 2, NOW()),
(1, '2023', 2, NOW()),
(1, 'Comprobantes', 1, NOW()),
(2, 'Mi Carpeta', NULL, NOW()),
(2, 'Contratos', 6, NOW()),
(2, 'Reportes', 6, NOW()),
(3, 'Documentos', NULL, NOW()),
(3, 'Recibos', 9, NOW()),
(3, 'Comprobantes', 9, NOW()),
(4, 'Principal', NULL, NOW()),
(4, 'Facturas 2024', 12, NOW()),
(4, 'Documentos Legales', 12, NOW()),
(5, 'Mi Almacenamiento', NULL, NOW()),
(5, 'RUC', 15, NOW()),
(5, 'Permisos', 15, NOW()),
(6, 'Inicio', NULL, NOW()),
(6, 'Descargas', 18, NOW()),
(7, 'Documentos', NULL, NOW());

INSERT INTO documents (user_id, folder_id, title, file_url, extracted_fields, original_filename, mime_type, created_at) VALUES 
(1, 2, 'Factura 2024-001', 'https://storage.example.com/doc1.pdf', '{"numero": "001", "monto": "1500.00", "fecha": "2024-01-15", "ruc": "20123456789"}', 'factura_001.pdf', 'application/pdf', NOW()),
(1, 2, 'Factura 2024-002', 'https://storage.example.com/doc2.pdf', '{"numero": "002", "monto": "2350.50", "fecha": "2024-01-20", "ruc": "20123456789"}', 'factura_002.pdf', 'application/pdf', NOW()),
(1, 3, 'Comprobante Pago', 'https://storage.example.com/doc3.pdf', '{"comprobante": "CP-001", "total": "3800.00", "fecha": "2024-02-10"}', 'comprobante.pdf', 'application/pdf', NOW()),
(1, 4, 'Factura 2023-001', 'https://storage.example.com/doc4.pdf', '{"numero": "001", "monto": "1200.00", "fecha": "2023-12-15", "ruc": "20123456789"}', 'factura_2023.pdf', 'application/pdf', NOW()),
(1, 5, 'Boleta 001', 'https://storage.example.com/doc5.pdf', '{"boleta": "001", "monto": "450.00", "fecha": "2024-01-05"}', 'boleta_001.pdf', 'application/pdf', NOW()),
(2, 7, 'Contrato Servicios', 'https://storage.example.com/doc6.pdf', '{"contrato": "CS-2024", "partes": "2", "fecha": "2024-01-01"}', 'contrato.pdf', 'application/pdf', NOW()),
(2, 7, 'Acuerdo Confidencial', 'https://storage.example.com/doc7.pdf', '{"tipo": "NDA", "fecha": "2024-01-10"}', 'nda.pdf', 'application/pdf', NOW()),
(2, 8, 'Reporte Mensual', 'https://storage.example.com/doc8.pdf', '{"mes": "enero", "ano": "2024", "estado": "completo"}', 'reporte_ene.pdf', 'application/pdf', NOW()),
(3, 10, 'Recibo 001', 'https://storage.example.com/doc9.pdf', '{"numero": "001", "monto": "850.00", "fecha": "2024-01-08"}', 'recibo_001.pdf', 'application/pdf', NOW()),
(3, 10, 'Recibo 002', 'https://storage.example.com/doc10.pdf', '{"numero": "002", "monto": "1250.00", "fecha": "2024-01-15"}', 'recibo_002.pdf', 'application/pdf', NOW()),
(3, 11, 'Comprobante Venta', 'https://storage.example.com/doc11.pdf', '{"tipo": "factura", "serie": "F01", "numero": "001"}', 'comprobante_venta.pdf', 'application/pdf', NOW()),
(4, 13, 'Factura 2024-100', 'https://storage.example.com/doc12.pdf', '{"numero": "100", "monto": "5600.00", "fecha": "2024-02-01", "ruc": "20987654321"}', 'factura_100.pdf', 'application/pdf', NOW()),
(4, 13, 'Factura 2024-101', 'https://storage.example.com/doc13.pdf', '{"numero": "101", "monto": "3200.00", "fecha": "2024-02-05", "ruc": "20987654321"}', 'factura_101.pdf', 'application/pdf', NOW()),
(4, 14, 'Escritura Propiedad', 'https://storage.example.com/doc14.pdf', '{"tipo": "escritura", "propiedad": "terreno"}', 'escritura.pdf', 'application/pdf', NOW()),
(5, 16, 'Certificado RUC', 'https://storage.example.com/doc15.pdf', '{"ruc": "20123456789", "razon_social": "Empresa XYZ"}', 'certificado_ruc.pdf', 'application/pdf', NOW()),
(5, 16, 'RUC Vigencia', 'https://storage.example.com/doc16.pdf', '{"ruc": "20123456789", "estado": "activo"}', 'ruc_vigencia.pdf', 'application/pdf', NOW()),
(5, 17, 'Permiso Municipal', 'https://storage.example.com/doc17.pdf', '{"tipo": "permiso", "municipalidad": "Lima"}', 'permiso_muni.pdf', 'application/pdf', NOW()),
(6, 19, 'Documento Descargar 1', 'https://storage.example.com/doc18.pdf', '{"titulo": "Doc1"}', 'doc1.pdf', 'application/pdf', NOW()),
(7, NULL, 'Factura Suelta', 'https://storage.example.com/doc19.pdf', '{"numero": "999", "monto": "750.00"}', 'factura_999.pdf', 'application/pdf', NOW()),
(8, NULL, 'Documento Sin Clasificar', 'https://storage.example.com/doc20.pdf', NULL, 'documento.pdf', 'application/pdf', NOW());

INSERT INTO tags (user_id, name, created_at) VALUES 
(1, 'Importante', NOW()),
(1, 'Facturas', NOW()),
(1, 'Urgente', NOW()),
(1, '2024', NOW()),
(1, 'Revisado', NOW()),
(2, 'Contratos', NOW()),
(2, 'Legales', NOW()),
(2, 'Confidencial', NOW()),
(3, 'Recibos', NOW()),
(3, 'Pagado', NOW()),
(4, 'Pendiente', NOW()),
(4, 'Verificado', NOW()),
(5, 'Oficial', NOW()),
(5, 'Archivo', NOW()),
(6, 'Descargado', NOW());

INSERT INTO document_tags (document_id, tag_id) VALUES 
(1, 2), (1, 4),
(2, 2), (2, 4),
(3, 2), (3, 5),
(4, 2),
(5, 2),
(6, 6), (6, 7),
(7, 6), (7, 7), (7, 8),
(8, 6),
(9, 9), (9, 10),
(10, 9), (10, 10),
(11, 9),
(12, 11), (12, 4),
(13, 11), (13, 4),
(14, 7), (14, 12),
(15, 13),
(16, 13), (16, 14),
(17, 13),
(18, 15),
(19, 1),
(20, 1);

INSERT INTO sync_events (user_id, entity_type, entity_id, operation, timestamp) VALUES 
(1, 'folder', 1, 'create', NOW() - INTERVAL '7 days'),
(1, 'folder', 2, 'create', NOW() - INTERVAL '7 days'),
(1, 'document', 1, 'create', NOW() - INTERVAL '6 days'),
(1, 'document', 2, 'create', NOW() - INTERVAL '5 days'),
(1, 'document', 1, 'update', NOW() - INTERVAL '4 days'),
(1, 'folder', 3, 'create', NOW() - INTERVAL '3 days'),
(1, 'document', 3, 'create', NOW() - INTERVAL '2 days'),
(2, 'folder', 6, 'create', NOW() - INTERVAL '7 days'),
(2, 'folder', 7, 'create', NOW() - INTERVAL '6 days'),
(2, 'document', 6, 'create', NOW() - INTERVAL '5 days'),
(2, 'document', 7, 'create', NOW() - INTERVAL '4 days'),
(2, 'document', 8, 'create', NOW() - INTERVAL '3 days'),
(3, 'folder', 9, 'create', NOW() - INTERVAL '6 days'),
(3, 'document', 9, 'create', NOW() - INTERVAL '5 days'),
(3, 'document', 9, 'update', NOW() - INTERVAL '4 days'),
(3, 'document', 10, 'create', NOW() - INTERVAL '3 days'),
(4, 'folder', 12, 'create', NOW() - INTERVAL '5 days'),
(4, 'document', 12, 'create', NOW() - INTERVAL '4 days'),
(4, 'document', 13, 'create', NOW() - INTERVAL '3 days'),
(5, 'folder', 15, 'create', NOW() - INTERVAL '4 days'),
(5, 'document', 15, 'create', NOW() - INTERVAL '3 days'),
(5, 'document', 15, 'update', NOW() - INTERVAL '2 days'),
(6, 'folder', 18, 'create', NOW() - INTERVAL '3 days'),
(7, 'document', 19, 'create', NOW() - INTERVAL '2 days'),
(8, 'document', 20, 'create', NOW() - INTERVAL '1 day');

COMMIT;
